#---------------------------------------------------------------------
management:
  security:
    enabled: false

#---------------------------------------------------------------------
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: admin
    hikari:
     maximum-pool-size: 15
     minimum-idle: 15
     auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update #create #none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog/liquibase-changeLog.xml
  devtools:
    add-properties: true
    livereload: 
      enabled: true
      port: 35729
    remote.restart.enabled: true
    
    
#---------------------------------------------------------------------
server:
  host: 10.9.80.233
  port: 8443
  
#---------------------------------------------------------------------

logging.level.org.hibernate.SQL: DEBUG #Logs SQL statements at DEBUG level.
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE #Logs placeholder values in SQL.
logging.level.org.hibernate.type: TRACE #Detailed logging for all Hibernate types.

tds.featurelist.property: tds.rogueradio.enable,tds.ovt.terminalstats.enable,tds.api.default.satellite