#---------------------------------------------------------------------
management:
  security:
    enabled: false

#---------------------------------------------------------------------
spring:
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false 
    spring.h2.console.settings.web-allow-others: false
  datasource:
    url: jdbc:h2:file:/data/demo
    username: postgres
    password: admin
    driverClassName: org.h2.Driver
#    hikari:
#     maximum-pool-size: 15
#     minimum-idle: 15
#     auto-commit: true
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    hibernate:
      ddl-auto: create #update #none #create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_schema: pilotautomation
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog/liquibase-changeLog.xml
  devtools:
    add-properties: true
    livereload: 
      enabled: true
      port: 35729
    remote.restart.enabled: true
    
    
#---------------------------------------------------------------------
server:
  host: locahost
  port: 8443
  
#---------------------------------------------------------------------
springdoc:
  api-docs:
    path: /api-docs-json
  swagger-ui:
    enabled: true
    path: /api-docs-ui
    operationsSorter: method

#---------------------------------------------------------------------
