#---------------------------------------------------------------------
spring.profiles.active: dev

---
spring:
  config:
    activate:
      on-profile: dev
    location: classpath:application-dev.yml
    name: application-dev.yml
    additional-location:
---
spring:
  config:
    activate:
      on-profile: test
    location: classpath:application-test.yml
    name: application-test.yml
    additional-location:
---
spring:
  config:
    activate:
      on-profile: prod
    location: classpath:application-prod.yml
    name: application-prod.yml
    additional-location:
---
#---------------------------------------------------------------------

springdoc:
  version: v1.1
  api-docs:
    enabled: true
    path: /api-docs-json
  swagger-ui:
    enabled: true
    path: /api-docs-ui
    operationsSorter: method

Info.contact: 
  name: "Prashant Mishra"
  email: email@email.com
  url: https://voyager.com/